[package]
name = "run"
version = "1.0.0"
edition = "2024"

[dependencies]
console_stuff = "0.2.1"
libc = "0.2.174"
miette = { version = "7.6.0", features = ["fancy"] }
strsim = "0.11.1"
thiserror = "2.0.12"
walkdir = "2.5.0"
